### ISSUE TITLE
Doesn't show album art on songs not officially on apple music

### ISSUE THREAD

**Issue by Aviviviviveee** [NextFire/apple-music-discord-rpc#10]
Hence the title, it doesn't show the album art of a custom downloaded song (just shows the apple music logo)
And when I play a custom song by a certain artist it sometimes shows the album art of a different song they made instead, even tho I'm playing a mashup I made (Martin Garrix & MOTi's Virus and DJ EB & HoodSaded's Emotions)
<img width="582" alt="Screenshot 2022-02-19 at 16 55 52" src="https://user-images.githubusercontent.com/98211163/154808358-8b7a5d65-d0be-43ff-89d8-c6064a7c4e42.png">

Also how do I get the absolute cloned repo path or whatever to work (Keeps throwing "Error5 missing input/output")

**Comment by NextFire** [comment]
> Hence the title, it doesn't show the album art of a custom downloaded song

Actually the cover feature relies on the iTunes Store API, so it only works with album correctly tagged and available on Apple Music/iTunes.

> Also how do I get the absolute cloned repo path or whatever to work

In the Finder you can right click on the folder `apple-music-discord-rpc` you cloned/downloaded, maintain `alt` and choose the option *Copy apple-music-discord-rpc as Pathname* or something like this.

**Comment by Aviviviviveee** [comment]
<img width="462" alt="Screenshot 2022-02-19 at 17 01 59" src="https://user-images.githubusercontent.com/98211163/154808621-d8ce7434-3eb2-459d-a60b-dc68254a4dff.png">
Lemme try this https://www.reddit.com/r/MacOS/comments/kbko61/launchctl_broken/gpv2to1/

**Comment by Aviviviviveee** [comment]
<img width="580" alt="Screenshot 2022-02-19 at 17 06 09" src="https://user-images.githubusercontent.com/98211163/154808744-1a74a637-5934-475a-ac3d-1e6b98eb82a2.png">
+ idk why it's showing the this, Promises of Tears is an unreleased song

<img width="885" alt="Screenshot 2022-02-19 at 17 06 34" src="https://user-images.githubusercontent.com/98211163/154808758-39a8932a-03a2-4ba6-871b-fd368157b3ca.png">
And this is what it actually looks like

**Comment by Aviviviviveee** [comment]
also when is the script suppose to automatically boot up? it says when you login but login where? and do i need to have terminal open etc, + the issues in the message above and my first message (regarding the first message i mean the issue where it shows album art of an artist even tho it's not that song)

**Comment by NextFire** [comment]
> idk why it's showing me this, Promises of Tears is an unreleased song

```
nextfire@MacBook-Pro-de-Nam ~> http 'https://itunes.apple.com/search?media=music&entity=album&limit=1&term=Avicii AVĪCI'
{
    "resultCount": 1,
    "results": [
        {
            "amgArtistId": 2097113,
            "artistId": 298496035,
            "artistName": "Avicii",
            "artistViewUrl": "https://music.apple.com/us/artist/avicii/298496035?uo=4",
            "artworkUrl100": "https://is2-ssl.mzstatic.com/image/thumb/Music125/v4/82/9b/58/829b585d-5c1b-4cca-98fd-a1b6c9929d1c/source/100x100bb.jpg",
            "artworkUrl60": "https://is2-ssl.mzstatic.com/image/thumb/Music125/v4/82/9b/58/829b585d-5c1b-4cca-98fd-a1b6c9929d1c/source/60x60bb.jpg",
            "collectionCensoredName": "AVĪCI (01) - EP",
            "collectionExplicitness": "explicit",
            "collectionId": 1440899018,
            "collectionName": "AVĪCI (01) - EP",
            "collectionPrice": 4.99,
            "collectionType": "Album",
            "collectionViewUrl": "https://music.apple.com/us/album/av%C4%ABci-01-ep/1440899018?uo=4",
            "contentAdvisoryRating": "Explicit",
            "copyright": "℗ 2017 Avicii Music AB, under exclusive license to Universal Music AB",
            "country": "USA",
            "currency": "USD",
            "primaryGenreName": "Dance",
            "releaseDate": "2017-08-11T07:00:00Z",
            "trackCount": 6,
            "wrapperType": "collection"
        }
    ]
}
```

Well as I said, it is a fuzzy search so it can fails pretty easily.

> also when is the script suppose to automatically boot up? it says when you login but login where?

After setting the LaunchAgent .plist the script is automatically loaded when you log in your macOS session with no action needed.

**Comment by Aviviviviveee** [comment]
<img width="583" alt="Screenshot 2022-02-19 at 17 21 24" src="https://user-images.githubusercontent.com/98211163/154809333-61c2ddd6-7576-4e9c-93ab-8872bc7f6ec5.png">
Welp, this is incorrect
<img width="871" alt="Screenshot 2022-02-19 at 17 21 53" src="https://user-images.githubusercontent.com/98211163/154809347-72c20d16-3e09-4e7a-ba3d-4880f1730960.png">

also i still have to quick start it cuz this didnt work
<img width="675" alt="Screenshot 2022-02-19 at 17 22 57" src="https://user-images.githubusercontent.com/98211163/154809408-3a7243b3-af65-4d8c-9998-5386bf9404f6.png">

**Comment by NextFire** [comment]
Can you show me your `moe.yuru.music-rpc.plist`?

**Comment by Aviviviviveee** [comment]
![Screenshot_2022-02-19_at_17 26 32 png](https://user-images.githubusercontent.com/98211163/154809546-36909bbe-99ce-495e-9582-47663b1139e7.jpeg)

<img width="577" alt="Screenshot 2022-02-19 at 17 28 30" src="https://user-images.githubusercontent.com/98211163/154809557-f3ff36ef-9c8d-46a2-af89-3416b39b2c0c.png">
Not from True, Pastis is from 2008

**Comment by NextFire** [comment]
The plist seems correct, maybe recheck deno location, it is located at `/usr/local/bin/deno` on my Mac (installed with Homebrew too). 

What appear when you `launchctl unload ~/Library/LaunchAgents/moe.yuru.music-rpc.plist` first then `launchctl load ~/Library/LaunchAgents/moe.yuru.music-rpc.plist` again?  Also please send me the output of `ls -l ~/Library/LaunchAgents/moe.yuru.music-rpc.plist`.

> Not from True, Pastis is from 2008

Well once again, I cannot really do anything with what the iTunes Search API returns aside adding an option in the script to disable it completely if it bother you too much.

**Comment by Aviviviviveee** [comment]
it didnt give me an error when doing the unloud and load now
![Screenshot_2022-02-19_at_17 50 07 png](https://user-images.githubusercontent.com/98211163/154810537-e3833733-28c3-4119-b37b-d96af5cb14c7.jpeg)

**Comment by NextFire** [comment]
> it didnt give me an error when doing the unloud and load now

Ok so the previous errors were probably just that the script was already loaded when you tried to `launchctl load` it I guess

**Comment by Aviviviviveee** [comment]
so i dont need terminal open now?

**Comment by NextFire** [comment]
Yes it should not be needed anymore (you can reboot to try).

**Comment by Aviviviviveee** [comment]
thnx a lot, it worked
<img width="588" alt="Screenshot 2022-02-19 at 18 05 20" src="https://user-images.githubusercontent.com/98211163/154811011-488af4e6-d4ff-40b6-86e4-492163b03e8e.png">

 also you dont need to disable it, i just find it weird that it cant even find the correct album art for released songs
<img width="865" alt="Screenshot 2022-02-19 at 18 05 58" src="https://user-images.githubusercontent.com/98211163/154811036-052bab75-0e7d-4047-b1bf-2c4de1f6d1c1.png">

**Comment by NextFire** [comment]
Alright then, I will close this issue for now if there nothing else to add
