### ISSUE TITLE
Shows me playing for 19k days lol

### ISSUE THREAD

**Issue by Aviviviviveee** [NextFire/apple-music-discord-rpc#11]
![Screenshot_2022-02-20_125216](https://user-images.githubusercontent.com/98211163/154843517-37034b06-a4c9-4d34-8caa-4959a8d2d309.png)
my friend showed me this. it only shows the insane amount of days when you check via the friends list
<img width="260" alt="Screenshot 2022-02-20 at 13 54 48" src="https://user-images.githubusercontent.com/98211163/154843552-928b860f-083e-4d82-bf18-115458398c28.png">
this for example

when you actually check my status the amount of days isnt there

**Comment by NextFire** [comment]
Wait https://github.com/harmonyland/discord_rpc/pull/12 to be merged then I will remove the `start` timestamp from the activity.
