### ISSUE TITLE
Displaying Incorrect Album Artwork

### ISSUE THREAD

**Issue by gravo-lan** [NextFire/apple-music-discord-rpc#14]
When playing music on a playlist, the album artwork is sometimes inaccurate, and the artwork of another song in the playlist is displayed.

If it helps, I'm running MacOS Monterey `12.2.1`, deno version `1.19.3` with discord `Stable 118821 (4751bf9)`.

Expected Result:
<img width="281" alt="Screenshot 2022-03-16 at 1 48 25 PM" src="https://user-images.githubusercontent.com/66149576/158524835-066cc6ba-cae6-4b7d-bb01-69b03a06e388.png">

Actual Result:
<img width="278" alt="Screenshot 2022-03-16 at 1 46 22 PM" src="https://user-images.githubusercontent.com/66149576/158524628-b1cb831b-9063-4cfc-af74-2c878e5e3496.png">

**Comment by NextFire** [comment]
Please pull the latest commit, it should fix these errors.
