### ISSUE TITLE
Album Art Incorrect every time

### ISSUE THREAD

**Issue by jsuri5356** [NextFire/apple-music-discord-rpc#16]
Hi!

I was recently encountering a bug where the album art for every song would be incorrect (it would would be an album art from my library, but not one that is the correct one). It started occuring right around the time I updated to macOS 12.3, though I am unsure if that is a direct cause of this issue. Thank you for creating this and I hope you are able to fix this issue!

<img width="261" alt="Screen Shot 2022-03-23 at 4 25 28 PM" src="https://user-images.githubusercontent.com/52750297/159789505-a378479b-bfde-4cd4-90b5-6394a337c081.png">

<img width="410" alt="Screen Shot 2022-03-23 at 4 25 45 PM" src="https://user-images.githubusercontent.com/52750297/159789508-41a74e95-faab-439a-b2c8-37b25db2176c.png">

**Comment by NextFire** [comment]
Are you using the latest version https://github.com/NextFire/apple-music-discord-rpc/commit/35ff67cb4a55bb7686fdc52169d2d77a635a678f ?

**Comment by jsuri5356** [comment]
Yes I am! After running git pull however, should I also replace the .plist files as well? (I am using the daemon mode for this). Thank you for the incredibly fast response!

**Comment by NextFire** [comment]
Can you send your `infos.json` file?

**Comment by NextFire** [comment]
Hmm it is an old cache, did you restarted the script after you pulled the changes?

**Comment by jsuri5356** [comment]
Running either of those commands gives me this error. 
<img width="427" alt="image" src="https://user-images.githubusercontent.com/52750297/159793358-59140cfa-7ed2-4fc8-a9c0-615972f817d5.png">

**Comment by NextFire** [comment]
well, just log out then log in instead I guess

**Comment by jsuri5356** [comment]
After doing that, it has just completly stopped working. That's really weird, I will try to uninstall and reinstall it and see if that helps. If I am unable to unload/load the plist file, any suggestions? The error I'm getting is the one above. Thank you again for your fast responses!

**Comment by NextFire** [comment]
Yeah try to uninstall and reinstall following  the steps in the readme

**Comment by jsuri5356** [comment]
After doing a clean reinstall, everything seems to be working perfectly! Thank you so much for your help in this, hope you enjoy the rest of your day!

**Comment by NextFire** [comment]
Nice, I will close this issue then
