### ISSUE TITLE
rich presence not being set in macOs 12.3

### ISSUE THREAD

**Issue by furudean** [NextFire/apple-music-discord-rpc#19]
script seems to run just fine (including good outputs in console) but i can't get the rich presence to be set on discord after upgrading to monterey from big sur

let me know if i can help with any debug information!!!

<details>
<summary>log</summary>
<pre>
<code>Client {
  options: { id: "773825528921849856" },
  ipc: DiscordIPC {},
  user: {
    id: "385196786438111233",
    username: "merilynn",
    discriminator: "1234",
    avatar: "0dbce623a026a372c3647d0d4d8df485",
    bot: false,
    flags: 528,
    premium_type: 2
  },
  config: {
    cdn_host: "cdn.discordapp.com",
    api_endpoint: "//discord.com/api",
    environment: "production"
  },
  token: undefined,
  tokenExpires: undefined,
  application: undefined
}
isOpen: true
state: playing
props: {
  class: "fileTrack",
  id: 9459,
  index: 1378,
  name: "Black Cat",
  persistentID: "BA16756898C727D0",
  databaseID: 6380,
  dateAdded: "2022-04-02T21:38:21.000Z",
  time: "3:58",
  duration: 238.4969940185547,
  artist: "Broadcast",
  albumArtist: "Broadcast",
  composer: "",
  album: "Tender Buttons",
  genre: "Leftfield/Synth-pop/Experimental",
  bitRate: 320,
  sampleRate: 44100,
  trackCount: 14,
  trackNumber: 2,
  discCount: 1,
  discNumber: 1,
  size: 9615553,
  volumeAdjustment: 0,
  year: 2005,
  comment: "Tumen Collection",
  eq: "",
  kind: "MPEG audio file",
  mediaKind: "song",
  modificationDate: "2022-03-31T05:56:44.000Z",
  enabled: true,
  start: 0,
  finish: 238.4969940185547,
  playedCount: 0,
  skippedCount: 0,
  compilation: false,
  rating: 0,
  bpm: 0,
  grouping: "",
  bookmarkable: false,
  bookmark: 0,
  shufflable: true,
  lyrics: "",
  category: "",
  description: "",
  episodeNumber: 0,
  unplayed: false,
  sortName: "",
  sortAlbum: "",
  sortArtist: "Broadcast",
  sortComposer: "",
  sortAlbumArtist: "Broadcast",
  loved: false,
  disliked: false,
  albumLoved: false,
  albumDisliked: false,
  cloudStatus: "unknown",
  work: "",
  movement: "",
  movementNumber: 0,
  movementCount: 0,
  location: {},
  playerPosition: 41.65399932861328
}
infos: {
  artwork: "https://is2-ssl.mzstatic.com/image/thumb/Music/v4/9b/5d/13/9b5d1300-f307-b0ed-b616-20bd3af30d45/sour...",
  url: "https://music.apple.com/us/album/tender-buttons/291071689?uo=4"
}</code></pre>
</details>

**Comment by NextFire** [comment]
Hello! These logs looks fine, are you still running into this issue?

**Comment by furudean** [comment]
it seemed to start working again randomly after confirming a prompt to allow the script to access the music app

**Comment by NextFire** [comment]
All right, feel free to reopen the issue if you encounter the same problem again.

**Comment by BoogieMonster1O1** [comment]
same issue for me - rich presence wasn't being set.
it started working once I got the prompt and I allowed it to access the music app
