### ISSUE TITLE
Trying to remove this program and folder continues to reappear

### ISSUE THREAD

**Issue by jamesf-hub** [NextFire/apple-music-discord-rpc#24]
https://user-images.githubusercontent.com/43358890/168947253-4bf1be6f-6d20-4050-8663-151c5ae9b386.mov

**Comment by NextFire** [comment]
I believe that the reappearing folder contains a cache.json file, meaning that the script is still running in background.
Follow the instructions [here](https://github.com/NextFire/apple-music-discord-rpc/blob/c49e3363c44841f7dfefb41ecdcf42c81fea2ddb/README.md#uninstall) to disable and remove the launch agent first.
