### ISSUE TITLE
Discord displays "Playing Apple Music" instead of "Listening to Apple Music" 

### ISSUE THREAD

**Issue by eduardstal** [NextFire/apple-music-discord-rpc#28]
How Spotify shows up: 
![image](https://user-images.githubusercontent.com/39627934/179121424-5bc37358-1d84-4b99-8380-846c574da7a0.png)

How `apple-music-discord-rpc` shows up 
![image](https://user-images.githubusercontent.com/39627934/179121448-d668f249-4ab9-48d0-9721-eac9ca78b89e.png)

How `apple-music-discord-rpc` should show up :)
![image](https://user-images.githubusercontent.com/39627934/179121585-0244a587-f434-4220-ba06-2fdf1a19c5db.png)

**Comment by NextFire** [comment]
The "listening to" status cannot be set by the userspace RPC protocol. Only bots and Spotify can use it.

**Comment by sorae42** [comment]
@NextFire pin this issue
