### ISSUE TITLE
Trouble with Music Details

### ISSUE THREAD

**Issue by taorou** [NextFire/apple-music-discord-rpc#3]
Yo! I just got it up and running on my mac (i'm on M1), and it's showing me this:

![Screen Shot 2021-05-02 at 8 59 46 PM](https://user-images.githubusercontent.com/81917631/116840045-5af7f180-ab89-11eb-90ab-ddffb91b2cc4.png)

any idea how i could fix this?

**Comment by taorou** [comment]
> Yo! I just got it up and running on my mac (i'm on M1), and it's showing me this:
> 
> ![Screen Shot 2021-05-02 at 8 59 46 PM](https://user-images.githubusercontent.com/81917631/116840045-5af7f180-ab89-11eb-90ab-ddffb91b2cc4.png)
> 
> any idea how i could fix this?

i dunno if it's supposed to show like that, but i probably did something wrong. Can't see the music details

**Comment by NextFire** [comment]
Hello! Can you tell me what song you were listening and, while playing this song, send me the result of the execution in Terminal of `osascript -e "tell application \"Music\"" -e "get properties of current track" -e "end tell"`

**Comment by taorou** [comment]
It was happening with all of the songs i was listening to at the time. I started playing my playlist and executed the command in terminal, and it shows `29:39: execution error: Music got an error: Can’t get properties of current track. (-1728)`

**Comment by NextFire** [comment]
Mmmh that's odd. Can you retry with a local track (not Apple Music) if it wasn't the case? If it was, it looks like the provided Apple Script interface that my script relies on is to be blamed here :/

**Comment by taorou** [comment]
![Screen Shot 2021-05-03 at 10 05 24 AM](https://user-images.githubusercontent.com/81917631/116907942-26bb1a00-abf7-11eb-81de-b36292ea881b.png)

tried it with a song on my computer, and it works just fine! I guess it cant get the info from songs on the actual streaming platform

**Comment by NextFire** [comment]
Ok so I guess we run into the same limitation i described here https://github.com/NextFire/apple-music-discord-rpc/issues/1#issuecomment-748795840, I should update the README to acknowledge this limitation

**Comment by NextFire** [comment]
See #4 for further possible developments

**Comment by taorou** [comment]
oh wait a sec
so I downloaded music from the Apple Music thing into my library, and now it's showing the song?
I guess it cant show stuff that isnt there

**Comment by NextFire** [comment]
Oh well I'm not a Apple Music subscriber, I couldn't test myself haha

Anyway if it does not work well everywhere, it's still a bit broken...
