### ISSUE TITLE
Some songs are not able to show their details(album photo)

### ISSUE THREAD

**Issue by HarlaownLY-Nijigasaki** [NextFire/apple-music-discord-rpc#32]
First of all, the discord rich presence is great. Nearly all the music I listen can show their information, I love it very much. It just only has some bugs that I am currently facing, so I post it here to see is there any chance to fix it. There are some of them that they will just show the Apple Music icon (not the song itself album photo).
Here is the bug I am facing:
------------------------------------------------------------------------------
This is one of the problem I am facing. It cannot show the album photo
<img width="289" alt="Problem 1" src="https://user-images.githubusercontent.com/110438989/182282337-249d6bd2-0fe4-4acb-9028-25837ce4348f.png">

This is the different song but this is the song in the same album
<img width="289" alt="Same Ablum but diff artist" src="https://user-images.githubusercontent.com/110438989/182282519-6e56c63f-56a1-4ac8-86a3-6d9e39a3edf9.png">

This is the same problem as above , I just provide one more example here.
<img width="289" alt="Problem 2" src="https://user-images.githubusercontent.com/110438989/182282635-e5e4fcf9-cc63-4c46-84b8-00090f7b9ecd.png">

This is the different song but this is the song in the same album
<img width="289" alt="Same Ablum 2but diff artist" src="https://user-images.githubusercontent.com/110438989/182282651-4d834c87-7974-4444-b9fe-82307a17d226.png">
-----------------------------------------------------------------------------

**Comment by NextFire** [comment]
The name of the artists (or the name of the album) on your tracks might differ from the ones on Apple Music. It often happens with multi-artists works and when it is the case the match easily fails.
