### ISSUE TITLE
Error when starting service.

### ISSUE THREAD

**Issue by JOOT49** [NextFire/apple-music-discord-rpc#34]
Error is as such: ``'Error: Failure while executing; `/bin/launchctl enable gui/501/homebrew.mxcl.apple-music-discord-rpc` exited with 125.'
`
`Using this on non admin computer, and using SU to switch to an admin account, should I not use brew and manually install?

**Comment by NextFire** [comment]
I have never tried Homebrew on a non-admin account. The script install should works fine.
