### ISSUE TITLE
Hey, could you add a tutorial?

### ISSUE THREAD

**Issue by DockyZeta** [NextFire/apple-music-discord-rpc#35]
So, uhh, I tried to install it but it didn't work and i have no idea how to run it, so a step tutorial would be amazing.

**Comment by darkmastermindz** [comment]
@DockyZeta Running the scripts in the readme seems to work - but can confirm that the packaged version doesn't work @NextFire.

[deno runtime](https://deno.land/#installation)

`brew install deno`

> Scripts
>
> Install
>
> Install [Deno](https://deno.land/) then clone the repository and execute [install.sh](https://github.com/NextFire/apple-> > music-discord-rpc/blob/main/scripts/install.sh):
>```
> git clone https://github.com/NextFire/apple-music-discord-rpc.git
> cd apple-music-discord-rpc/
> ./scripts/install.sh
> ```
> It will copy the [launch agent](https://github.com/NextFire/apple-music-discord-rpc/blob/main/scripts/moe.yuru.music-> > rpc.plist) into ~/Library/LaunchAgents/ and correctly edit it.
>
>Uninstall
>
>cd apple-music-discord-rpc/
>./scripts/uninstall.sh
>cd ../
>rm -rf apple-music-discord-rpc/

**Comment by NextFire** [comment]
Hmm it is working fine on my side with the brew method. Can you send me the logs at `/usr/local/var/apple-music-discord-rpc`?

**Comment by DockyZeta** [comment]
it installed everything, but what do i do after? 
> Installed launch agent at ~/Library/LaunchAgents/moe.yuru.music-rpc.plist
> Successfully loaded launch agent.
Should I run the deno runtime thing? if so, how?

**Comment by DockyZeta** [comment]
did this on accident, my bad

**Comment by NextFire** [comment]
Once the launch agent is loaded, things should works correctly

**Comment by DockyZeta** [comment]
But there's no rich presence or anything, should i select an application from game activity? perhaps apple music? ill try.

**Comment by NextFire** [comment]
Can you send me the log file? (`/usr/local/var/apple-music-discord-rpc/music-rpc.log`)

**Comment by NextFire** [comment]
Oh sorry, music-rpc.log in the folder you cloned

**Comment by DockyZeta** [comment]
I couldn't find (/usr/local/var/apple-music-discord-rpc/music-rpc.log), sorry. it's blank
I didn't even find apple-music-discord-rpc in /var/, only homebrew. Did i do this wrong?

**Comment by NextFire** [comment]
> Oh sorry, music-rpc.log in the folder you cloned

I fixed my prompt in the next comment, sorry

**Comment by DockyZeta** [comment]
it's all just "env: deno: No such file or directory". I must've installed it incorrectly

**Comment by DockyZeta** [comment]
oh my god im sorry

**Comment by DockyZeta** [comment]
i closed it on accident again

**Comment by NextFire** [comment]
Did you install `deno` with homebrew?

**Comment by DockyZeta** [comment]
no, i used "curl -fsSL https://deno.land/install.sh | sh" from their website since homebrew returned "Running `brew update --auto-update`...
error: Not a valid ref: refs/remotes/origin/master
fatal: ambiguous argument 'refs/remotes/origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
"

**Comment by DockyZeta** [comment]
............. you can ignore me i guess i always keep pressing this

**Comment by DockyZeta** [comment]
damn button

**Comment by NextFire** [comment]
Alright, can you give me the output of `which deno`?

**Comment by DockyZeta** [comment]
deno not found, I guess i don't have deno installed

**Comment by NextFire** [comment]
You may have downloaded it but it is not added to PATH. I have never used the curl install, maybe it asked you to update your PATH afterward.

**Comment by NextFire** [comment]
It appears that it is installed in `~/.deno/bin/` (https://deno.land/x/install@v0.1.6/install.sh?source=#L32) which is not supported by my install script anyway. I will update my script to not hardcode `PATH` in the plist but it will still require that deno is added to your current shell `PATH`

**Comment by NextFire** [comment]
@DockyZeta Please pull the new fix, add your `deno` install to your PATH (so `which deno` can find it) then relaunch the install script.
