### ISSUE TITLE
Does this work on Windows aswell?

### ISSUE THREAD

**Issue by WebCappuccino** [NextFire/apple-music-discord-rpc#38]
Hello, windows user here. I would like to know if this can run on windows, because after installing everything and following the guide it doesn't work, and if it's not possible to run this with windows yet-- would it be possible to make a windows version? thanks!

**Comment by NextFire** [comment]
The script only works on macOS as it heavily relies on some automations that only the macOS app provides.
Not using Windows I do not have plan on investigate further on it.
