### ISSUE TITLE
Region exclusive songs unable to show album 

### ISSUE THREAD

**Issue by HarlaownLY-Nijigasaki** [NextFire/apple-music-discord-rpc#39]
I found that this tool is using the US region to search for song details. I wonder if there is a chance to change the region?

for example:
https://music.apple.com/jp/album/木漏れ日のエール/1556034319?i=1556034320

this is a Japan region exclusive album.
If I use US region to search, it will not show anything.

**Comment by NextFire** [comment]
You can add `country: "JP"` in the `params` object here:

https://github.com/NextFire/apple-music-discord-rpc/blob/b5d1a74d3106d96096cb61f6e3b0c1d754710097/music-rpc.ts#L131-L136

**Comment by HarlaownLY-Nijigasaki** [comment]
Although it still not show the album detail on discord status, thank you for your reply :)
