### ISSUE TITLE
Delay

### ISSUE THREAD

**Issue by ghost** [NextFire/apple-music-discord-rpc#40]
There is a delay when i skip, pause, and play a song in the rpc.

**Comment by NextFire** [comment]
AppleScript does not provide any publish-subscribe capability to retrieve the player state so the script has to poll it every 15s.
Why 15s? There is a rate limit imposed by Discord on updating the user presence (https://discord.com/developers/docs/rich-presence/how-to#updating-presence).

Well I guess the script could still poll every second and report to Discord only when there is an actual update but even that would not be perfect and certainly be heavily resource consuming...
