### ISSUE TITLE
Rich Presence Client does not work anymore

### ISSUE THREAD

**Issue by JyojiFujisaki** [NextFire/apple-music-discord-rpc#43]
Starting next week, it will be two weeks since the Discord Rich Presence Client can no longer be used (as for my case).
I did a reinstall using Homebrew, which was unsuccessful.

**Comment by NextFire** [comment]
Can you send me:
- the output of `brew services`
- the content of `/usr/local/var/apple-music-discord-rpc/music-rpc.log`
- the output when you manually run `music-rpc.ts`

**Comment by JyojiFujisaki** [comment]
The output of `brew services`:

![brew services output](https://user-images.githubusercontent.com/48890266/202919989-18dcf02b-3f78-4c40-b8db-060b5d5cbf52.png)

The content of `/usr/local/var/apple-music-discord-rpc/music-rpc.log`:

[music-rpc.log](https://github.com/NextFire/apple-music-discord-rpc/files/10050439/music-rpc.log)

The output when I manually run `music-rpc.ts`

![music-rps ts manual execution](https://user-images.githubusercontent.com/48890266/202920479-634b9871-8702-4857-a850-7ca4bf3c1a58.png)

Addition to the manual execution of `music-rpc.ts`:

![music-rps ts manual execution addition](https://user-images.githubusercontent.com/48890266/202920867-402c5454-7c05-4c61-a00e-5c79a0f700f5.png)

Many apologies for my delayed response.
I appreciate your efforts as well as your willingness to help.

**Comment by NextFire** [comment]
So there is no presence even when you manually run `music-rpc.ts`? The different outputs/logs seem correct to me...

**Comment by JyojiFujisaki** [comment]
That's correct.

**Comment by NextFire** [comment]
Did you check that presences are correctly enabled within the Discord client settings? 

Maybe try to reinstall Discord, all I see on the manual run is that the script correctly handshakes the Discord RPC and is getting track infos from Apple Music.

**Comment by JyojiFujisaki** [comment]
`[...] all I see on the manual run is that the script correctly handshakes the Discord RPC and is getting track infos from Apple Music.`

So did I.
I'll try to re-install the Discord client.

**Comment by NextFire** [comment]
Hmm, let's try something.
- Edit `~/Library/Application\ Support/discord/settings.json` and add `"DANGEROUS_ENABLE_DEVTOOLS_ONLY_ENABLE_IF_YOU_KNOW_WHAT_YOURE_DOING": true` then relaunch Discord. 
This should enable the access to the JS console (opt+cmd+i).
- Launch `music-rpc.ts` and inspect the Discord console. If everything work well you should see `SET_ACTIVITY` messages like this:

<img width="1140" alt="Capture d’écran 2022-11-20 à 14 27 59" src="https://user-images.githubusercontent.com/20094890/202921940-e37f6c71-7a41-4785-9c36-e9b537f002be.png">

Send me what you see here.

**Comment by JyojiFujisaki** [comment]
![screenshot](https://user-images.githubusercontent.com/48890266/202922521-e9207169-dd2a-465c-9b4a-68c7e9e7838b.png)

**Comment by JyojiFujisaki** [comment]
![screenshot 1](https://user-images.githubusercontent.com/48890266/202922610-9c00951b-f0c9-4dea-871e-097749706206.png)

**Comment by NextFire** [comment]
So the client is correctly receiving the activity but does not rebroadcast it.
If you have indeed enabled presence sharing within the settings, it may be a bug of the Discord client outside of the scope of the script.
Are presences working with other applications that support it?

**Comment by JyojiFujisaki** [comment]
![issue](https://user-images.githubusercontent.com/48890266/202923107-3b911df3-b1e7-4044-8e3f-bfa0ace68945.png)

I just changed a setting that was previously disabled. I remember having this function enabled by default. It must have changed during an update. Accordingly, I would like to apologize for the inconvenience caused by this inconspicuous feature.

Thank you for helping me with all the tools at your disposal. Stay healthy and have a pleasant day.
