### ISSUE TITLE
Random album artwork on certain local tracks

### ISSUE THREAD

**Issue by strafe** [NextFire/apple-music-discord-rpc#46]
Both tracks shown below are local tracks, one seems to somehow be linked to an Apple Music/iTunes track. Here is a [direct link](https://media.discordapp.net/external/HVlIOP_WpEoacbn5vlVE1xSAK6pEeqS5ShnoQBVZn-A/https/is4-ssl.mzstatic.com/image/thumb/Music113/v4/d3/81/92/d381927b-dd84-f761-1a3b-63b102735c13/jacket-959742.jpg/100x100bb.jpg) to the album artwork that is being shown.

Clicking `Play on Apple Music` does nothing, but it doesn't seem to work for Apple Music tracks either in my case.

<img width="200" alt="CleanShot 2023-01-01 at 21 30 22@2x" src="https://user-images.githubusercontent.com/15663890/210185098-0c33f0ba-783f-4f15-9a89-373a35a0143e.png">

<img width="200" alt="CleanShot 2023-01-01 at 21 31 14@2x" src="https://user-images.githubusercontent.com/15663890/210185122-ddded65d-5211-4430-9396-3e121402ad08.png">

macOS 12.4
Discord Stable

**Comment by strafe** [comment]
Seems [this](https://music.apple.com/us/album/scent-of-mandarin-orange-namu-plane-vol-3-single/1490567008) is where it's grabbing the artwork from. Note that there are a few similar(?) fields. The artist of my track is `namu` and the album is `vol. III`.

**Comment by strafe** [comment]
I had a look at why it's happening, my two cents would be to calculate the [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance) between the artist name and or album name and decide of a threshold to confirm if it's a match. As `NAMU PLANE` is quite far from `namu`.

**Comment by NextFire** [comment]
The matching is made by a "quite dumb" search of `${artist} ${album}` on the iTunes API. This sometimes leads to wrong results and unfortunately there is no easy solution besides maybe a better tagging of your tracks to exactly match the ones on Apple Music.

**Comment by strafe** [comment]
These tracks aren't on Apple Music/iTunes so it would never be possible to point it towards the correct track. Probably out of the scope of this project, but the ability to upload local track artwork to a image hosting site and use that URL for the icon would be a neat addition
