### ISSUE TITLE
trouble parsing.

### ISSUE THREAD

**Issue by o0000ol** [NextFire/apple-music-discord-rpc#49]
- if CJK language is mixed with English & Number, artwork will not be displayed.
- if asterisk included, artwork will not be displayed.

## Sample
<a href="https://music.apple.com/us/album/1584618491">[https://music.apple.com/us/album/1584618491]</a>
<img width="511" alt="Screenshot 2023-01-26 at 5 44 31" src="https://user-images.githubusercontent.com/69783875/214686175-069ece25-dbc3-463f-aa3e-af61dfefc7aa.png">

<a href="https://music.apple.com/us/album/1569281731">[https://music.apple.com/us/album/1569281731]</a>
<img width="513" alt="Screenshot 2023-01-26 at 5 51 08" src="https://user-images.githubusercontent.com/69783875/214687692-6c6175c5-a44e-4213-915d-921df4ce5677.png">

## Solution: Change parse domain
+ solved sometime displayed incorrect artwork.
`https://tools.applemediaservices.com/api/apple-media/music/US/search.json?types=songs&limit=1&term=${album}+${artist}+${name}`

<img width="786" alt="Screenshot 2023-01-26 at 5 36 34" src="https://user-images.githubusercontent.com/69783875/214684854-e07335e3-a151-42d1-99b5-cb4eca1353c7.png">

---

**Comment by NextFire** [comment]
Is this API endpoint public? I can't find any documentation on the web

**Comment by NextFire** [comment]
It should be fixed in #62. Feel free to reopen if you still encounter this issue.

**Comment by TheMoonThatRises** [comment]
The second song is fixed, but for the first one, it still fails to return a result. I've noticed that you can only get a song response from iTunes' api is to only input the song and album name are inputted, and not the artist.
