### ISSUE TITLE
Use custom uploaded artwork for local files

### ISSUE THREAD

**Issue by Crunnie** [NextFire/apple-music-discord-rpc#50]
I'm pretty sure Cider had a feature like that and it worked well, is it possible you could implement it into this as well?

**Comment by NextFire** [comment]
At first glance this would require to
- get the music track location in the filesystem (AppleScript?)
- extract the cover art (ffmpeg can do it - maybe use a wasm version to avoid the need to install another dependency on the user side)
- push it to a hosting site (???)

I'm quite lazy to work on it right now but it looks doable. If anyone wants to develop it feel free to open a pr.

**Comment by sorae42** [comment]
You should use a music database (such as MusicBrainz) to find the cover album first since it's not very ideal to push the image to a hosting site everytime.
