### ISSUE TITLE
Launch Agents

### ISSUE THREAD

**Issue by Finnasaurus** [NextFire/apple-music-discord-rpc#51]
as far as I'm aware (which is little), brew install doesn't actually automatically create the plist in launch agent anymore on the M1 Mac, I've tried reinstalling too but to no avail.

had to resort to adding the app to apple's startup app manually, any suggestion to do it more elegantly?

the error in question is
```Error: Permission denied @ rb_sysopen - /Users/finn/Library/LaunchAgents/homebrew.mxcl.apple-music-discord-rpc.plist```

but upon looking through the folder "LaunchAgents", the plist file doesn't even exist

**Comment by NextFire** [comment]
Can you try 
`rm -f /Users/finn/Library/LaunchAgents/homebrew.mxcl.apple-music-discord-rpc.plist` (you may need to sudo it)
`brew services stop apple-music-discord-rpc`
`brew services start apple-music-discord-rpc`
and report me the output of `brew services`

**Comment by Finnasaurus** [comment]
`Name                    Status User File
apple-music-discord-rpc none   root`

**Comment by NextFire** [comment]
Send me `brew services info apple-music-discord-rpc`

**Comment by Finnasaurus** [comment]
sorry, was buy for the week

```
apple-music-discord-rpc (homebrew.mxcl.apple-music-discord-rpc)
Running: ✘
Loaded: ✘
Schedulable: ✘
```

**Comment by NextFire** [comment]
Hmm, re-execute `brew services start apple-music-discord-rpc` and resend me `brew services info apple-music-discord-rpc`.
If everything goes well, the output should be
```
apple-music-discord-rpc (homebrew.mxcl.apple-music-discord-rpc)
Running: ✔
Loaded: ✔
Schedulable: ✘
User: <...>
PID: <...>
```

**Comment by Finnasaurus** [comment]
hey man, the problem was that I couldn't launcher with ```brew services start```

![Untitled 4](https://user-images.githubusercontent.com/37584785/219407948-62952b42-4490-4995-b83a-6688b37730b5.png)

**Comment by NextFire** [comment]
Well, let's try fixing the perms
```
sudo chown -R $(id -u):$(id -g) ~/Library/LaunchAgents/
chmod 755 ~/Library/LaunchAgents/
rm -f Library/LaunchAgents/homebrew.mxcl.apple-music-discord-rpc.plist
brew services start apple-music-discord-rpc
```
If it still not works, it may be a homebrew bug

**Comment by Finnasaurus** [comment]
this seemed to have helped with the loading issue

```
finn@Mac-mini ~ % brew services info apple-music-discord-rpc
apple-music-discord-rpc (homebrew.mxcl.apple-music-discord-rpc)
Running: ✘
Loaded: ✔
Schedulable: ✘
```

**Comment by NextFire** [comment]
You may have to restart the system then confirm it is working fine
