### ISSUE TITLE
CPU 100% Bug

### ISSUE THREAD

**Issue by Kili2108** [NextFire/apple-music-discord-rpc#53]
I am writing this because I wanted to report a bug that the CPU Usage goes up to 100% as you can see here

![image](https://user-images.githubusercontent.com/61068014/219936235-e0c8718e-62f0-41e2-8ae2-5c1be622db2f.png)

Thats all about the information I have.
I hope you can resolve the bug, because with almost 100% CPU it's not really usable.

**Comment by NextFire** [comment]
Sorry for my lack of reply so far, is this still happening now?
