### ISSUE TITLE
No Song Art on streamed music.

### ISSUE THREAD

**Issue by paramveersii** [NextFire/apple-music-discord-rpc#56]
<img width="350" alt="Screenshot 2023-04-03 at 19 38 02" src="https://user-images.githubusercontent.com/121735202/229597670-5de7554a-f917-4f77-8e70-45a7702e5567.png">

you cool project I love it it used to work fine for me but recently my cover art is not there. I am streaming the music and its not local!

**Comment by NextFire** [comment]
Can you provide me an Apple Music link to this song?

**Comment by paramveersii** [comment]
https://music.apple.com/gb/album/around-the-world/893959767?i=893959800

**Comment by NextFire** [comment]
Ah I guess the script is looking for an album from `m.o.v.e` instead of `Various Artists`, that's why there is no results
