### ISSUE TITLE
Says INSTALL SUCCESS but just doesnt work

### ISSUE THREAD

**Issue by daixhi** [NextFire/apple-music-discord-rpc#57]
Maybe this might help?

user@MacBook-Pro apple-music-discord-rpc % ls -la scripts/
total 24
drwxr-xr-x   5 prakriti  staff  160 Apr 16 05:57 .
drwxr-xr-x  13 prakriti  staff  416 Apr 16 06:00 ..
-rwxr-xr-x   1 prakriti  staff  804 Apr 16 05:57 install.sh
-rw-r--r--   1 prakriti  staff  674 Apr 16 05:57 moe.yuru.music-rpc.plist
-rwxr-xr-x   1 prakriti  staff  231 Apr 16 05:57 uninstall.sh

**Comment by NextFire** [comment]
Please send `music-rpc.log` (should be in the project folder)

Also check in Discord that `Settings > Activity Privacy > Display current activity as a status message` is enabled

**Comment by daixhi** [comment]
[music-rpc.log](https://github.com/NextFire/apple-music-discord-rpc/files/11240994/music-rpc.log)

**Comment by NextFire** [comment]
It looks like it does not find the Discord socket. Is your Discord client up to date (stable channel) and unmodified?

**Comment by daixhi** [comment]
Looks Stable and is unmodified

Stable 189617 (5a59d26) 
Host 0.0.274 
OS X 10.15.7 (22.2.0)

**Comment by NextFire** [comment]
Can you try to restart you computer? If it still does not work, you might check the Discord console following these steps: https://github.com/NextFire/apple-music-discord-rpc/issues/43#issuecomment-1321221961

**Comment by NextFire** [comment]
I also just pushed a new release to update discord_rpc

**Comment by daixhi** [comment]
My Application Support Folder didn't have a Discord folder, so the console couldn't be opened. The new release worked almost immediately though. Thank you~
