### ISSUE TITLE
deno Requests New Permissions Often

### ISSUE THREAD

**Issue by Avakining** [NextFire/apple-music-discord-rpc#58]
Most (though not every) time I open Apple Music after not opening it for a bit. This is probably every time deno updates? Is there a way to make it remember the permissions and/or make it not have a new section in System Settings/Privacy & Security/Accessibility?

Not sure if this is a bug with this or with deno, either (sorry)

**Comment by NextFire** [comment]
Yeah I believe it is a macOS thing to ask for permissions again after each (deno binary) update for security reasons. I don't think there is any workaround to this.
