### ISSUE TITLE
Homebrew service not starting

### ISSUE THREAD

**Issue by EyadElshaer** [NextFire/apple-music-discord-rpc#64]
when I play any music on the Apple Music app on the MacBook it doesn't show up on discord I tried restarting the Mac but nothing helped

**Comment by NathanielH-snek** [comment]
Yeah for me it only works if i manually run it in the terminal

**Comment by EyadElshaer** [comment]
> Are you launching it from brew or path?

How can I know ?

**Comment by NathanielH-snek** [comment]
What do you type into the terminal to run it in terminal? Did you install with homebrew?

**Comment by EyadElshaer** [comment]
> What do you type into the terminal to run it in terminal? Did you install with homebrew?

I downloaded homebrew and used the terminal to run it

**Comment by allycatty** [comment]
Are we supposed to create an application in the discord dev portal? If so where are we suppose to put the config stuff.

**Comment by allycatty** [comment]
I've tried installing manually and with brew in every way I could on multiple macs, tried upgrading deno, and it just doesn't work at all. I'm guessing this project is abandoned? Shame Apple can't just make something and the community has to do their work for them.

**Comment by NathanielH-snek** [comment]
> I've tried installing manually and with brew in every way I could on multiple macs, tried upgrading deno, no luck whatsoever.
> 
> Are we supposed to create an application in the discord dev portal? Or is it possibly and issue with the change in Discord username discriminators? 

Have you tried launching the application manually the way I mentioned above. It works, I think the problem is the automatic script to have it launch on startup. Probably broken by macOS at some point.

**Comment by NextFire** [comment]
@EyadElshaer If you installed it with Homebrew, check that the script is running fine on a manual run with `music-rpc.ts` in the terminal as @NathanielH-snek suggested. 

@allycatty The script should run as it is and works fine with the new username system.

If you encounter some issues with the launch agent, try the troubleshooting steps in https://github.com/NextFire/apple-music-discord-rpc/issues/51. If it is not working at all, please assure that activity sharing is well enabled in your Discord client settings.

**Comment by mjcarvin** [comment]
I'm running into the same problem. I went through the troubleshooting steps here and in #51  ...

1. manually running `music-rpc.ts` from the terminal works and activity sharing is turned on in Discord.

2. `brew services` output

```
Name                    Status       User    File
apple-music-discord-rpc error  19968 michael ~/Library/LaunchAgents/homebrew.mxcl.apple-music-discord-rpc.plist
```

3.  `brew services info apple-music-discord-rpc` output

```
brew services info apple-music-discord-rpc
apple-music-discord-rpc (homebrew.mxcl.apple-music-discord-rpc)
Running: ✘
Loaded: ✔
Schedulable: ✘
```

4. `brew services start apple-music-discord-rpc` output

```
brew services start apple-music-discord-rpc
Bootstrap failed: 5: Input/output error
Try re-running the command as root for richer errors.
Error: Failure while executing; `/bin/launchctl bootstrap gui/501 /Users/michael/Library/LaunchAgents/homebrew.mxcl.apple-music-discord-rpc.plist` exited with 5.
```

5. File permissions

```
-rw-r--r--   1 michael  staff   953 Jun 13 11:59 homebrew.mxcl.apple-music-discord-rpc.plist
```

**Comment by NextFire** [comment]
@mjcarvin Do you happen to use an Apple Silicon Mac?

**Comment by mjcarvin** [comment]
No, Intel MBP - skylake from 2016.

**Comment by EyadElshaer** [comment]
> @mjcarvin Do you happen to use an Apple Silicon Mac?

Nope using a hackintosh

**Comment by NathanielH-snek** [comment]
I do run an AS mac and I'm having the same issue although I haven't spent a lot of time troubleshooting. I'll see if I can figure it out later.

**Comment by mjcarvin** [comment]
> I've updated the formula which previously had a linting issue https://github.com/NextFire/homebrew-tap/commit/093eb083a746c0e1ffae232f6ddb079341df7db2.
I am not sure that it will resolve this issue but can you brew update && brew reinstall nextfire/tap/apple-music-discord-rpc && brew services restart nextfire/tap/apple-music-discord-rpc and check brew services info apple-music-discord-rpc again?


```
brew services info apple-music-discord-rpc

apple-music-discord-rpc (homebrew.mxcl.apple-music-discord-rpc)
Running: ✘
Loaded: ✔
Schedulable: ✘
```

```
brew services

Name                    Status       User    File
apple-music-discord-rpc error  19968 michael ~/Library/LaunchAgents/homebrew.mxcl.apple-music-discord-rpc.plist
sleepwatcher            started      michael ~/Library/LaunchAgents/homebrew.mxcl.sleepwatcher.plist
```

**Comment by NextFire** [comment]
@mjcarvin Can you paste the content of the generated launch agent?

**Comment by NextFire** [comment]
Is it the raw content of your .plist? Should have been some XML.
The `PATH` is fine if it contains at least `osascript` and `deno` (check with `which`).
Then if both `/usr/local/opt/apple-music-discord-rpc/bin/music-rpc.ts` and `/usr/local/var/apple-music-discord-rpc` exist, I don't see any reason for it not working... :/
(The `music-rpc.log` should have been located in `/usr/local/var/apple-music-discord-rpc`, not in the home root, I'll fix that at least...)

**Comment by mjcarvin** [comment]
That was the raw content. Here's the xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>EnvironmentVariables</key>
	<dict>
		<key>PATH</key>
		<string>/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin</string>
	</dict>
	<key>KeepAlive</key>
	<true/>
	<key>Label</key>
	<string>homebrew.mxcl.apple-music-discord-rpc</string>
	<key>LimitLoadToSessionType</key>
	<array>
		<string>Aqua</string>
		<string>Background</string>
		<string>LoginWindow</string>
		<string>StandardIO</string>
		<string>System</string>
	</array>
	<key>ProgramArguments</key>
	<array>
		<string>/usr/local/opt/apple-music-discord-rpc/bin/music-rpc.ts</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
	<key>StandardErrorPath</key>
	<string>/Users/michael/music-rpc.log</string>
	<key>WorkingDirectory</key>
	<string>/usr/local/var/apple-music-discord-rpc</string>
</dict>
</plist>
```

`which osascript` and `which deno` return good paths, so that's fine.

music-rpc.ts is in `/usr/local/opt/apple-music-discord-rpc/bin/` and running it manually from my home root works fine.

_This is not right on my end_
```
from the xml

<key>WorkingDirectory</key>
	<string>/usr/local/var/apple-music-discord-rpc</string>
```

```
ls -la /usr/local/var

total 0
drwxrwxr-x   4 michael  admin  128 May 20 14:22 .
drwxr-xr-x  14 root     wheel  448 May 20 14:02 ..
drwxrwxr-x   4 michael  admin  128 May 20 14:10 homebrew
drwxr-xr-x   3 michael  admin   96 May 20 14:22 run
```

**Comment by mjcarvin** [comment]
> `/usr/local/var/apple-music-discord-rpc` is automatically created when the service starts (re-checked on my side) so no problem here

Huh. I don't see it in my /usr/local/var folder.

> As a last resort can you try the shell scripts install method [in the README](https://github.com/NextFire/apple-music-discord-rpc#shell-scripts)? You may have better luck here...

I just did and it started right up when I ran the install script.

Thanks for making the time to help diagnose this. I really appreciate it.

**Comment by NextFire** [comment]
> Huh. I don't see it in my /usr/local/var folder.

Yeah somehow Homebrew can't even start the generated launch agent...

> I just did and it started right up when I ran the install script.

Perfect! 

> Thanks for making the time to help diagnose this. I really appreciate it.

You're welcome! Thank you for your quick replies.
