### ISSUE TITLE
Spotify song search for songs that are in another language on spotify

### ISSUE THREAD

**Issue by anthonyhuang07** [NextFire/apple-music-discord-rpc#78]
This may be difficult to fix, but some Japanese songs on Apple Music are titled in english (e.g. SEVENTEEN by YOASOBI) but on Spotify it's under the Japanese title "セブンティーン". So when you press the search on spotify button for the song, it returns no results. I don't know how you could fix this other than some translation feature, but this is very nitpicky so I understand if this doesn't get resolved.

**Comment by NextFire** [comment]
I can't think of any simple/robust solution to this problem that could easily cover a majority of cases.
While I still have no intention of implementing it, I can refer you to suggestion #71 which you may find relevant.

**Comment by hyotaime** [comment]
I just changed the iTunes country to jp in the 146th line and solved it by applying #71 as well.
