### ISSUE TITLE
Enhancement Request: Adding Play/Pause Icons to Discord Status Display

### ISSUE THREAD

**Issue by KoukeNeko** [NextFire/apple-music-discord-rpc#86]
![image](https://github.com/NextFire/apple-music-discord-rpc/assets/111033412/be23d7b5-8ad6-4ec2-82cc-e6339a0487e1)
![image](https://github.com/NextFire/apple-music-discord-rpc/assets/111033412/57f456c3-55b4-44d6-9ecd-6ff274cd3d34)
I've been using apple-music-discord-rpc and I'm really enjoying the functionality it brings to Discord, allowing me to share what I'm listening to on Apple Music with my friends. It's been a great experience so far, and I appreciate all the work that has gone into this project.

I have a suggestion for a small enhancement that could improve the user experience even further. It would be really helpful if there were small play/pause icons next to the track information in the Discord status. This would provide a quick visual indication of whether the music is currently playing or paused, making the status more informative at a glance.

# Proposal

- Add a small play icon (▶️) when a track is playing.
- Add a small pause icon (⏸) when the music is paused.

I believe this addition would not only enhance the aesthetic appeal but also provide functional value by quickly conveying the playback status to anyone viewing the Discord profile.

# Possible Implementation
I'm not sure about the technical feasibility, but I assume this could be implemented by modifying the status update logic to include these icons based on the playback state.

**Comment by NextFire** [comment]
Thank you for taking the time to write a proposal. As I'm trying to reproduce Spotify's native presence as much as possible, keeping an active presence while a song is paused is not an option.

Feel free to fork this project and customize the script to your convenience:
* If you want to show something while a track is paused, add a handler here: https://github.com/NextFire/apple-music-discord-rpc/blob/55e1058c000c2fa3b8285c56f4fd67c66dbdd293/music-rpc.ts#L303
* For the small icon, we're looking here: https://github.com/NextFire/apple-music-discord-rpc/blob/55e1058c000c2fa3b8285c56f4fd67c66dbdd293/music-rpc.ts#L273-L276
Add a `small_image` URL and `small_text` to this object.
