### ISSUE TITLE
More a question, than an issue

### ISSUE THREAD

**Issue by Som3Guyy** [NextFire/apple-music-discord-rpc#87]
Is there a way to modify the code realistically in order to support betterdiscord? Just wondering

**Comment by Som3Guyy** [comment]
Btw I’m on MacOS 14.3.1 and installed everything alr via homebrew but then realized that I run betterdiscord and not regular discord

**Comment by NextFire** [comment]
AFAIK BetterDiscord is still the official client with some modifications and I don't immediately see why this script wouldn't work with it unless they've modified the rich presence IPC interface.
