### ISSUE TITLE
After git pull, it broke

### ISSUE THREAD

**Issue by wl03355609** [NextFire/apple-music-discord-rpc#9]
I used agent mode, after doing pull
Discord wasn't showing apple music
So i did "./music-rpc.ts"
and terminal gave this

error: TS2420 [ERROR]: Class 'NamedPipe' incorrectly implements interface 'Conn'.
  Type 'NamedPipe' is missing the following properties from type 'Conn': readable, writable
export class NamedPipe implements Deno.Conn {
             ~~~~~~~~~
    at https://deno.land/x/namedpipe@0.0.3/src/client.ts:27:14

TS2739 [ERROR]: Type 'NamedPipe' is missing the following properties from type 'Conn': readable, writable
      return await connect(path);
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://raw.githubusercontent.com/harmonyland/discord_rpc/1d41f3c830a66d4f2699774bc3ec5b44cceb3a46/src/util.ts:33:7

Found 2 errors.

bc i was upgrading from the old npm method
so i did remove the whole folder and tried again, still output this
any ideas?

**Comment by NextFire** [comment]
Oh nevermind, I can reproduce the error, I will investigate it

**Comment by NextFire** [comment]
I temporarily fixed the issue in the latest commit eb3b5902771dea31d903bf70eb546d85d893acf0

**Comment by wl03355609** [comment]
Thanks, I'll get it and hope this get figured out
I like your work, thanks for make it happened 👍

**Comment by DjDeveloperr** [comment]
You can now upgrade discord_rpc to 0.3.0 to fix the issue than using fork
