### ISSUE TITLE
Hi i have a major problem while adding the fromulae

### ISSUE THREAD

**Issue by Apple4787Microbitter** [NextFire/apple-music-discord-rpc#90]
I click the hyperlink to the other GitHub page which contains the formulae. I have NO FUCKING IDEA what I do there. it says something like type this into terminal and blah blah but... the issue is what is the ⟨formula⟩ i have no idea I'm not a programmer. Please update that page.

**Comment by NextFire** [comment]
Here are the steps required to install and run the script, make sure you understand every command before proceeding (for security reasons):

- Install [Homebrew](https://brew.sh):
```sh
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```
- Execute the three commands listed here: https://github.com/NextFire/apple-music-discord-rpc?tab=readme-ov-file#install

**Comment by Apple4787Microbitter** [comment]
Thanks
