### ISSUE TITLE
Change the "Playing" status to "Listening"

### ISSUE THREAD

**Issue by Hackerman74** [NextFire/apple-music-discord-rpc#91]
It'd be nice if you could change the "Playing a game" and "Playing" status to "Listening" etc. not sure if the status itself is usable whenever but it'd be a nice touch 

<img width="203" alt="Screenshot 2024-06-06 at 01 29 34" src="https://github.com/NextFire/apple-music-discord-rpc/assets/59330189/f6f28df7-9c48-4bd8-9f0b-a554470f6cce">

**Comment by NextFire** [comment]
https://github.com/NextFire/apple-music-discord-rpc/issues/85

**Comment by skyer1a** [comment]
this is possible now
