### ISSUE TITLE
Hovering the headphones icon says "by by $artistname"

### ISSUE THREAD

**Issue by Avakining** [NextFire/apple-music-discord-rpc#97]
As shown in the screenshots, hovering over the headphone icon next to my name in the sidebar shows "by by $artistname" instead of just "by $artistname"

<img width="159" alt="Screenshot 2024-08-29 at 11 21 30" src="https://github.com/user-attachments/assets/8306063a-6920-4608-8b5b-10ba1cdae5c8">
<img width="200" alt="Screenshot 2024-08-29 at 11 23 40" src="https://github.com/user-attachments/assets/68d231ce-370a-4460-aefe-1d65fd0e3b7d">

**Comment by NextFire** [comment]
Oh I guess the "playing with" status already prefix this field with "by"
